apiVersion: v1
kind: Service
metadata:
  name: hello-python-backend-service
spec:
  selector:
    app: hello-python-backend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python-backend
spec:
  selector:
    matchLabels:
      app: hello-python-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python-backend
    spec:
      containers:
      - name: hello-python-backend
        image: hello-python-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: NAME 
          value: "Cesar A. Nogueira"